### ISSUE TITLE
progress import makes rendering slower

### ISSUE THREAD

**Issue by Aympab** [bourbonut/vtk-raytracing#1]
Hi, I noticed the import of Progress from rich makes the main rendering quite laggy

```python
from rich.progress import Progress
```

Or maybe [tqdm library](https://anaconda.org/conda-forge/tqdm) is faster ?

**Comment by bourbonut** [comment]
Hi, there is no issue with `rich`.
Check out the documentation if you need more information: https://rich.readthedocs.io/en/stable/progress.html
